/**
 * GhostYield Phase 1 — static illustrative candidates only.
 */

import type { GhostYieldCategoryMeta, GhostYieldCandidateRaw, YieldEnvironmentInputs } from './types';
import { scoreCandidates } from './scoring';

export const YIELD_SLEEVE_CATEGORIES: GhostYieldCategoryMeta[] = [
  {
    id: 'credit_income',
    label: 'Credit Income',
    blurb:
      'ETFs and funds focused on corporate loans and bonds. Yield often rises when credit spreads widen — you may be paid more to hold default and downgrade risk.',
  },
  {
    id: 'bdc_income',
    label: 'BDC Income',
    blurb:
      'Business development companies lend to private middle-market firms. NAV can swing with credit marks; distributions may include volatile components.',
  },
  {
    id: 'cef_credit',
    label: 'CEF Credit',
    blurb:
      'Leveraged closed-end funds trading at premiums or discounts to NAV. High payouts and structural leverage can amplify both income and NAV risk.',
  },
  {
    id: 'midstream_income',
    label: 'Midstream Income',
    blurb:
      'Energy infrastructure cash flows. Yield can look attractive when commodity volatility rises; equity and balance-sheet risk remain.',
  },
  {
    id: 'preferred_income',
    label: 'Preferred Income',
    blurb:
      'Hybrid securities — higher yields than many bonds, but rate sensitivity and issuer credit still matter. Resets and call features add complexity.',
  },
  {
    id: 'option_income',
    label: 'Option Income',
    blurb:
      'Covered-call and similar strategies trade upside for premium. Distribution stability can look good until the underlying trend shifts.',
  },
  {
    id: 'crypto_yield_coming_soon',
    label: 'Crypto Yield',
    blurb: 'Placeholder only for Phase 1.',
    comingSoon: true,
  },
  {
    id: 'cash_tbills',
    label: 'Cash / T-Bill Yield',
    blurb: 'Treasury and cash-like sleeves. Low credit drama, but reinvestment and real-return risk still exist.',
  },
];

export const GHOSTYIELD_SAMPLE_ENV: YieldEnvironmentInputs = {
  creditStress: 52,
  ratePressure: 48,
  volRegime: 44,
};

export const GHOSTYIELD_RAW_CANDIDATES: GhostYieldCandidateRaw[] = [
  {
    ticker: 'SGOV',
    name: 'iShares 0-3 Month Treasury Bond ETF',
    sleeveType: 'cash_tbills',
    yieldSource: 'T-bill interest — short government paper.',
    currentYield: 0.052,
    secYield: 0.051,
    navTrend1Y: 0.001,
    role: 'Liquidity ballast and yield on idle cash.',
    mainRisks: ['Reinvestment if rates fall', 'Not a credit hedge in a crisis'],
    bestUseCase: 'Parking cash with minimal duration.',
    avoidIf: 'You need equity-like upside.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'strong',
  },
  {
    ticker: 'HYG',
    name: 'iShares iBoxx $ High Yield Corporate Bond ETF',
    sleeveType: 'credit_income',
    yieldSource: 'Portfolio of high-yield corporate bonds — coupon-focused.',
    currentYield: 0.068,
    secYield: 0.067,
    navTrend1Y: 0.024,
    role: 'Credit beta satellite around investment-grade core.',
    mainRisks: ['Default cycle drawdowns', 'Spread widening'],
    bestUseCase: 'Sizing a modest junk sleeve with eyes open.',
    avoidIf: 'You cannot tolerate drawdowns.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0049,
  },
  {
    ticker: 'BKLN',
    name: 'Invesco Senior Loan ETF',
    sleeveType: 'credit_income',
    yieldSource: 'Floating-rate senior loans — coupon resets with short rates.',
    currentYield: 0.072,
    navTrend1Y: 0.015,
    role: 'Rate-hedge-ish credit sleeve; still lender risk.',
    mainRisks: ['Credit deterioration if economy weakens', 'Liquidity in stress'],
    bestUseCase: 'Rate-rise playbook alongside core bonds.',
    avoidIf: 'You assume “senior” means safe in a recession.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0065,
  },
  {
    ticker: 'JAAA',
    name: 'Janus Henderson AAA CLO ETF',
    sleeveType: 'credit_income',
    yieldSource: 'Tranches of CLO debt — structured credit cash flows.',
    currentYield: 0.061,
    navTrend1Y: 0.008,
    role: 'Higher carry than IG with structural subordination language to read.',
    mainRisks: ['CLO complexity', 'Underlying loan quality cycles'],
    bestUseCase: 'Investors who accept structured-product homework.',
    avoidIf: 'You want plain vanilla.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0025,
  },
  {
    ticker: 'ARDC',
    name: 'Ares Dynamic Credit Allocation Fund',
    sleeveType: 'credit_income',
    yieldSource: 'Flexible credit allocation across loans, bonds, CLOs — manager driven.',
    currentYield: 0.09,
    secYield: 0.092,
    navTrend1Y: -0.02,
    premiumDiscount: 0.02,
    leverage: 1.15,
    expenseRatio: 0.027,
    role: 'Actively managed credit sleeve with potential overlap to other holdings.',
    mainRisks: ['Manager risk', 'Liquidity mismatches', 'Leverage'],
    bestUseCase: 'Active credit satellite when you trust the process.',
    avoidIf: 'You already have heavy credit risk elsewhere.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'uncertain',
  },
  {
    ticker: 'PFF',
    name: 'iShares Preferred & Income Securities ETF',
    sleeveType: 'preferred_income',
    yieldSource: 'Preferred stock dividends (tax treatment varies).',
    currentYield: 0.059,
    navTrend1Y: 0.011,
    role: 'Income tilt with rate and financial-sector concentration.',
    mainRisks: ['Rate resets', 'Issuer-specific shocks', 'Hybrid equity/bond behavior'],
    bestUseCase: 'Part of a diversified income menu.',
    avoidIf: 'You need FDIC safety.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0046,
  },
  {
    ticker: 'BIZD',
    name: 'VanEck BDC Income ETF',
    sleeveType: 'bdc_income',
    yieldSource: 'Basket of BDC common equity dividends.',
    currentYield: 0.104,
    navTrend1Y: -0.04,
    role: 'Broad BDC beta in one wrapper.',
    mainRisks: ['Credit marks hit NAV', 'Regulatory and capital structure risk'],
    bestUseCase: 'Diversified BDC sleeve without picking one name.',
    avoidIf: 'You dislike equity-like volatility.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.004,
  },
  {
    ticker: 'ARCC',
    name: 'Ares Capital Corp',
    sleeveType: 'bdc_income',
    yieldSource: 'BDC dividends from middle-market lending.',
    currentYield: 0.092,
    navTrend1Y: -0.015,
    premiumDiscount: 0.06,
    role: 'Single-name flagship BDC exposure.',
    mainRisks: ['Concentration', 'Leverage inside the BDC', 'Premium can compress'],
    bestUseCase: 'When you accept single-manager idiosyncrasy.',
    avoidIf: 'You need broad diversification in one click.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'BXSL',
    name: 'Blackstone Secured Lending',
    sleeveType: 'bdc_income',
    yieldSource: 'BDC lending and fee-related economics — dividend forward.',
    currentYield: 0.088,
    navTrend1Y: 0.005,
    premiumDiscount: 0.04,
    role: 'Another large BDC print — overlap watch with ARCC peers.',
    mainRisks: ['Credit cycle', 'Premium risk', 'Correlation with other BDCs'],
    bestUseCase: 'Pairs due diligence against other BDCs before sizing.',
    avoidIf: 'You already own several BDCs.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'KIO',
    name: 'KKR Income Opportunities Fund',
    sleeveType: 'cef_credit',
    yieldSource:
      'Leveraged closed-end credit fund — distributions may include return of capital; premium to NAV can collapse.',
    currentYield: 0.118,
    secYield: 0.095,
    navTrend1Y: -0.09,
    navTrend3Y: -0.12,
    premiumDiscount: 0.14,
    leverage: 1.38,
    expenseRatio: 0.031,
    role: 'High carry credit sleeve — verify how much is ROC vs earnings.',
    mainRisks: ['NAV decay', 'High leverage', 'Rich premium', 'Return of capital labels'],
    bestUseCase: 'Only after reading distribution tax character.',
    avoidIf: 'You want simple, low-leverage income.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'weak',
  },
  {
    ticker: 'EMO',
    name: 'Clearbridge Energy MLP Opportunity Fund',
    sleeveType: 'cef_credit',
    yieldSource: 'Energy-linked income with CEF leverage — NAV can trail spot commodities.',
    currentYield: 0.105,
    navTrend1Y: -0.06,
    navTrend3Y: -0.08,
    premiumDiscount: 0.05,
    leverage: 1.28,
    role: 'Energy income + structural leverage.',
    mainRisks: ['Commodity correlation', 'Leverage', 'CEF discount volatility'],
    bestUseCase: 'Tactical sleeve when you accept energy path risk.',
    avoidIf: 'You want low volatility.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'TYG',
    name: 'Tortoise Energy Infrastructure Corp',
    sleeveType: 'cef_credit',
    yieldSource: 'Energy infrastructure income via CEF wrapper.',
    currentYield: 0.098,
    navTrend1Y: -0.03,
    premiumDiscount: -0.08,
    leverage: 1.22,
    role: 'Discounted CEF angle vs some peers at premium.',
    mainRisks: ['Sector cyclicality', 'Leverage', 'Policy/regulatory shifts'],
    bestUseCase: 'When you deliberately want energy infra exposure.',
    avoidIf: 'You fear prolonged commodity softness.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'SPE',
    name: 'Special Opportunities Fund',
    sleeveType: 'cef_credit',
    yieldSource: 'Opportunistic credit sleeve — CEF.',
    currentYield: 0.088,
    navTrend1Y: -0.024,
    premiumDiscount: 0.03,
    leverage: 1.18,
    role: 'Smaller print — liquidity and disclosure matter.',
    mainRisks: ['Liquidity', 'Strategy drift', 'Leverage'],
    bestUseCase: 'Niche CEF research only.',
    avoidIf: 'You need daily transparency and scale.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'low',
    distributionQuality: 'uncertain',
  },
  {
    ticker: 'BRW',
    name: 'Saba Capital Income & Opportunities Fund',
    sleeveType: 'cef_credit',
    yieldSource: 'Event / credit sleeve — follow filings closely.',
    currentYield: 0.112,
    navTrend1Y: -0.055,
    premiumDiscount: 0.1,
    leverage: 1.32,
    role: 'Special-sits flavor; overlap with other CEFs possible.',
    mainRisks: ['Strategy opacity', 'Premium', 'Leverage', 'NAV path'],
    bestUseCase: 'If you enjoy reading shareholder letters.',
    avoidIf: 'You dislike activism-style events.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'low',
    distributionQuality: 'weak',
  },
  {
    ticker: 'PEO',
    name: 'Petroleum & Resources Corp',
    sleeveType: 'cef_credit',
    yieldSource: 'Energy equity/income mix — check current policy.',
    currentYield: 0.072,
    navTrend1Y: 0.01,
    premiumDiscount: -0.05,
    leverage: 1.05,
    role: 'Lighter leverage example vs heavy CEF peers.',
    mainRisks: ['Energy path', 'Dividend policy changes'],
    bestUseCase: 'Relative-value CEF hunters.',
    avoidIf: 'You want zero energy.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'NML',
    name: 'Neuberger Berman MLP Income Fund',
    sleeveType: 'cef_credit',
    yieldSource: 'MLP-linked income — CEF leverage common.',
    currentYield: 0.095,
    navTrend1Y: -0.07,
    premiumDiscount: 0.02,
    leverage: 1.35,
    role: 'Energy yield sleeve; watch tax K-1 / structure.',
    mainRisks: ['NAV erosion streaks', 'Leverage', 'Tax complexity'],
    bestUseCase: 'Tax-aware investors only.',
    avoidIf: 'You hate K-1s and complexity.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'weak',
  },
  {
    ticker: 'SRV',
    name: 'NXG Cushing Midstream Energy Fund',
    sleeveType: 'midstream_income',
    yieldSource: 'Midstream energy distributions.',
    currentYield: 0.085,
    navTrend1Y: -0.02,
    premiumDiscount: 0.04,
    leverage: 1.2,
    role: 'Midstream carry with fund structure frictions.',
    mainRisks: ['Commodity softness', 'Dividend cuts in stress', 'CEF premium'],
    bestUseCase: 'When midstream is a deliberate strategic bet.',
    avoidIf: 'You need non-cyclical income.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'KYN',
    name: 'Kayne Anderson Energy Infrastructure Fund',
    sleeveType: 'midstream_income',
    yieldSource: 'Energy infrastructure portfolio — CEF.',
    currentYield: 0.09,
    navTrend1Y: -0.04,
    premiumDiscount: 0.06,
    leverage: 1.25,
    role: 'Established midstream/MLP CEF print.',
    mainRisks: ['Commodity correlation', 'Leverage', 'Regulatory'],
    bestUseCase: 'Energy infrastructure sleeve sizing.',
    avoidIf: 'You are overweight energy already.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'JEPI',
    name: 'JPMorgan Equity Premium Income ETF',
    sleeveType: 'option_income',
    yieldSource: 'Equity portfolio plus active covered-call premium.',
    currentYield: 0.075,
    secYield: 0.074,
    navTrend1Y: 0.08,
    role: 'Lower-vol tilt equity sleeve with call-writing drag on runaway rallies.',
    mainRisks: ['Capped upside in melt-ups', 'Distribution fluctuates'],
    bestUseCase: 'Equity income without full beta in calm tape.',
    avoidIf: 'You need full index upside.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'strong',
    expenseRatio: 0.0035,
  },
  {
    ticker: 'JEPQ',
    name: 'JPMorgan Nasdaq Equity Premium Income ETF',
    sleeveType: 'option_income',
    yieldSource: 'Nasdaq-100 aligned sleeve with active call writing.',
    currentYield: 0.078,
    navTrend1Y: 0.09,
    role: 'Growth-tilt option-income; same playbook caveats as JEPI.',
    mainRisks: ['Tech concentration', 'Call overwrite cap'],
    bestUseCase: 'Income with growth bias.',
    avoidIf: 'You fear concentrated mega-cap risk.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0035,
  },
];

export const GHOSTYIELD_SCORED_CANDIDATES = scoreCandidates(GHOSTYIELD_RAW_CANDIDATES);
