/**
 * GhostYield Phase 1 — static illustrative candidates only.
 */

import type { GhostYieldCategoryMeta, GhostYieldCandidateRaw, YieldEnvironmentInputs } from './types';
import { scoreCandidates } from './scoring';

export const YIELD_SLEEVE_CATEGORIES: GhostYieldCategoryMeta[] = [
  {
    id: 'cash_tbills',
    label: 'Cash / T-Bill Yield',
    blurb:
      'Treasury and cash-like sleeves. Low credit drama, but reinvestment and real-return risk still exist.',
  },
  {
    id: 'credit_income',
    label: 'Credit Income',
    blurb:
      'Corporate loans, high yield, CLO tranches, and similar. Yield often rises when spreads widen — you are paid to hold default and downgrade risk.',
  },
  {
    id: 'preferred_income',
    label: 'Preferred Income',
    blurb:
      'Hybrid securities — higher yields than many bonds, but rate sensitivity and issuer credit still matter. Resets and call features add complexity.',
  },
  {
    id: 'cef_credit',
    label: 'CEF Credit',
    blurb:
      'Closed-end credit funds with structural leverage. NAV quotes, premiums/discounts, and distribution tax character — including return of capital — matter as much as coupons.',
  },
  {
    id: 'special_opportunistic_income',
    label: 'Opportunistic / Special Situations Income',
    blurb:
      'Event-driven, activism-adjacent, or opportunistic credit sleeves — often idiosyncratic. Liquidity, filings, and strategy drift deserve extra skepticism alongside headline yield.',
  },
  {
    id: 'bdc_income',
    label: 'BDC Income',
    blurb:
      'Business development companies lend to private middle-market firms. NAV can swing with credit marks; distributions may include volatile components.',
  },
  {
    id: 'midstream_income',
    label: 'Midstream Income',
    blurb:
      'Energy infrastructure and pipeline-style cash flows. Yield can look rich when commodity volatility rises; equity, balance-sheet, and regulatory risk remain.',
  },
  {
    id: 'natural_resources_income',
    label: 'Natural Resources Income',
    blurb:
      'Oil, gas, and resource-linked equities or funds. Dividends track commodity cycles and corporate policy — not the same risk profile as plain midstream fee streams.',
  },
  {
    id: 'option_income',
    label: 'Option Income',
    blurb:
      'Covered-call and similar strategies trade upside for premium. Distribution stability can look good until the underlying trend shifts.',
  },
  {
    id: 'crypto_yield_coming_soon',
    label: 'Crypto Yield',
    blurb:
      'Staking, lending, and tokenized yield carry protocol, custody, and gap-risk concerns. GhostYield will add this sleeve when there is a defensible static frame — not in Phase 1.',
    comingSoon: true,
  },
];

export const GHOSTYIELD_SAMPLE_ENV: YieldEnvironmentInputs = {
  creditStress: 52,
  ratePressure: 48,
  volRegime: 44,
};

export const GHOSTYIELD_RAW_CANDIDATES: GhostYieldCandidateRaw[] = [
  {
    ticker: 'SGOV',
    name: 'iShares 0-3 Month Treasury Bond ETF',
    sleeveType: 'cash_tbills',
    structureLabel: 'ETF',
    yieldSource: 'T-bill interest — short government paper.',
    currentYield: 0.052,
    secYield: 0.051,
    navTrend1Y: 0.001,
    role: 'Liquidity ballast and yield on idle cash.',
    mainRisks: ['Reinvestment if rates fall', 'Not a credit hedge in a crisis'],
    bestUseCase: 'Parking cash with minimal duration.',
    avoidIf: 'You need equity-like upside.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'strong',
  },
  {
    ticker: 'HYG',
    name: 'iShares iBoxx $ High Yield Corporate Bond ETF',
    sleeveType: 'credit_income',
    structureLabel: 'ETF',
    yieldSource: 'Portfolio of high-yield corporate bonds — coupon-focused.',
    currentYield: 0.068,
    secYield: 0.067,
    navTrend1Y: 0.024,
    role: 'Credit beta satellite around investment-grade core.',
    mainRisks: ['Default cycle drawdowns', 'Spread widening'],
    bestUseCase: 'Sizing a modest junk sleeve with eyes open.',
    avoidIf: 'You cannot tolerate drawdowns.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0049,
  },
  {
    ticker: 'BKLN',
    name: 'Invesco Senior Loan ETF',
    sleeveType: 'credit_income',
    structureLabel: 'ETF',
    yieldSource: 'Floating-rate senior loans — coupon resets with short rates.',
    currentYield: 0.072,
    navTrend1Y: 0.015,
    role: 'Rate-hedge-ish credit sleeve; still lender risk.',
    mainRisks: ['Credit deterioration if economy weakens', 'Liquidity in stress'],
    bestUseCase: 'Rate-rise playbook alongside core bonds.',
    avoidIf: 'You assume “senior” means safe in a recession.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0065,
  },
  {
    ticker: 'JAAA',
    name: 'Janus Henderson AAA CLO ETF',
    sleeveType: 'credit_income',
    structureLabel: 'ETF',
    yieldSource: 'Tranches of CLO debt — structured credit cash flows.',
    currentYield: 0.061,
    navTrend1Y: 0.008,
    role: 'Higher carry than IG with structural subordination language to read.',
    mainRisks: ['CLO complexity', 'Underlying loan quality cycles'],
    bestUseCase: 'Investors who accept structured-product homework.',
    avoidIf: 'You want plain vanilla.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0025,
  },
  {
    ticker: 'ARDC',
    name: 'Ares Dynamic Credit Allocation Fund',
    sleeveType: 'cef_credit',
    structureLabel: 'CEF',
    yieldSource: 'Flexible credit sleeve inside a closed-end fund — loans, bonds, CLOs; manager and leverage matter.',
    currentYield: 0.09,
    secYield: 0.092,
    navTrend1Y: -0.02,
    premiumDiscount: 0.02,
    leverage: 1.15,
    expenseRatio: 0.027,
    role: 'Actively managed credit sleeve with potential overlap to other holdings.',
    mainRisks: ['Manager risk', 'Liquidity mismatches', 'Leverage'],
    bestUseCase: 'Active credit satellite when you trust the process.',
    avoidIf: 'You already have heavy credit risk elsewhere.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'uncertain',
  },
  {
    ticker: 'PFF',
    name: 'iShares Preferred & Income Securities ETF',
    sleeveType: 'preferred_income',
    structureLabel: 'ETF',
    yieldSource: 'Preferred stock dividends (tax treatment varies).',
    currentYield: 0.059,
    navTrend1Y: 0.011,
    role: 'Income tilt with rate and financial-sector concentration.',
    mainRisks: ['Rate resets', 'Issuer-specific shocks', 'Hybrid equity/bond behavior'],
    bestUseCase: 'Part of a diversified income menu.',
    avoidIf: 'You need FDIC safety.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0046,
  },
  {
    ticker: 'BIZD',
    name: 'VanEck BDC Income ETF',
    sleeveType: 'bdc_income',
    structureLabel: 'ETF',
    yieldSource: 'Basket of BDC common equity dividends.',
    currentYield: 0.104,
    navTrend1Y: -0.04,
    role: 'Broad BDC beta in one wrapper.',
    mainRisks: ['Credit marks hit NAV', 'Regulatory and capital structure risk'],
    bestUseCase: 'Diversified BDC sleeve without picking one name.',
    avoidIf: 'You dislike equity-like volatility.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.004,
  },
  {
    ticker: 'ARCC',
    name: 'Ares Capital Corp',
    sleeveType: 'bdc_income',
    structureLabel: 'Listed BDC (stock)',
    yieldSource: 'BDC dividends from middle-market lending.',
    currentYield: 0.092,
    navTrend1Y: -0.015,
    premiumDiscount: 0.06,
    role: 'Single-name flagship BDC exposure.',
    mainRisks: ['Concentration', 'Leverage inside the BDC', 'Premium can compress'],
    bestUseCase: 'When you accept single-manager idiosyncrasy.',
    avoidIf: 'You need broad diversification in one click.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'BXSL',
    name: 'Blackstone Secured Lending',
    sleeveType: 'bdc_income',
    structureLabel: 'Listed BDC (stock)',
    yieldSource: 'BDC lending and fee-related economics — dividend forward.',
    currentYield: 0.088,
    navTrend1Y: 0.005,
    premiumDiscount: 0.04,
    role: 'Another large BDC print — overlap watch with ARCC peers.',
    mainRisks: ['Credit cycle', 'Premium risk', 'Correlation with other BDCs'],
    bestUseCase: 'Pairs due diligence against other BDCs before sizing.',
    avoidIf: 'You already own several BDCs.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'KIO',
    name: 'KKR Income Opportunities Fund',
    sleeveType: 'cef_credit',
    structureLabel: 'CEF',
    yieldSource:
      'Leveraged closed-end credit fund — distributions may include return of capital; premium to NAV can collapse.',
    currentYield: 0.118,
    secYield: 0.095,
    navTrend1Y: -0.09,
    navTrend3Y: -0.12,
    premiumDiscount: 0.14,
    leverage: 1.38,
    expenseRatio: 0.031,
    role: 'High carry credit sleeve — verify how much is ROC vs earnings.',
    mainRisks: ['NAV decay', 'High leverage', 'Rich premium', 'Return of capital labels'],
    bestUseCase: 'Only after reading distribution tax character.',
    avoidIf: 'You want simple, low-leverage income.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'weak',
  },
  {
    ticker: 'EMO',
    name: 'Clearbridge Energy MLP Opportunity Fund',
    sleeveType: 'midstream_income',
    structureLabel: 'CEF',
    yieldSource: 'Midstream / energy infrastructure cash flows; closed-end structure adds leverage and NAV volatility.',
    currentYield: 0.105,
    navTrend1Y: -0.06,
    navTrend3Y: -0.08,
    premiumDiscount: 0.05,
    leverage: 1.28,
    role: 'Energy infrastructure income with levered fund mechanics.',
    mainRisks: ['Commodity correlation', 'Leverage', 'CEF discount/premium swings'],
    bestUseCase: 'Tactical sleeve when you accept energy path risk.',
    avoidIf: 'You want low volatility.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'TYG',
    name: 'Tortoise Energy Infrastructure Corp',
    sleeveType: 'midstream_income',
    structureLabel: 'CEF',
    yieldSource: 'Energy infrastructure distributions — pipeline and related assets inside a CEF wrapper.',
    currentYield: 0.098,
    navTrend1Y: -0.03,
    premiumDiscount: -0.08,
    leverage: 1.22,
    role: 'Discounted CEF angle vs some peers at premium.',
    mainRisks: ['Sector cyclicality', 'Leverage', 'Policy/regulatory shifts'],
    bestUseCase: 'When you deliberately want energy infrastructure exposure.',
    avoidIf: 'You fear prolonged commodity softness.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'SPE',
    name: 'Special Opportunities Fund',
    sleeveType: 'special_situations_income',
    structureLabel: 'CEF',
    yieldSource: 'Special situations and opportunistic positions — read filings; liquidity can be thin.',
    currentYield: 0.088,
    navTrend1Y: -0.024,
    premiumDiscount: 0.03,
    leverage: 1.18,
    role: 'Niche sleeve — disclosure and turnover matter.',
    mainRisks: ['Liquidity', 'Strategy drift', 'Leverage'],
    bestUseCase: 'Special-sits homework only.',
    avoidIf: 'You need daily transparency and scale.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'low',
    distributionQuality: 'uncertain',
  },
  {
    ticker: 'BRW',
    name: 'Saba Capital Income & Opportunities Fund',
    sleeveType: 'opportunistic_credit',
    structureLabel: 'CEF',
    yieldSource: 'Event- and activism-adjacent credit sleeve — follow tender offers and proxy language.',
    currentYield: 0.112,
    navTrend1Y: -0.055,
    premiumDiscount: 0.1,
    leverage: 1.32,
    role: 'Opportunistic credit; overlap with other event funds possible.',
    mainRisks: ['Strategy opacity', 'Premium', 'Leverage', 'NAV path'],
    bestUseCase: 'If you enjoy reading shareholder letters.',
    avoidIf: 'You dislike activism-style events.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'low',
    distributionQuality: 'weak',
  },
  {
    ticker: 'PEO',
    name: 'Petroleum & Resources Corp',
    sleeveType: 'natural_resources_income',
    structureLabel: 'CEF',
    yieldSource: 'Natural resource equities — dividend policy tied to commodity cycles and corporate strategy.',
    currentYield: 0.072,
    navTrend1Y: 0.01,
    premiumDiscount: -0.05,
    leverage: 1.05,
    role: 'Resource income sleeve with lighter leverage vs some energy CEFs.',
    mainRisks: ['Commodity price path', 'Dividend policy changes', 'Equity drawdowns'],
    bestUseCase: 'When you deliberately want resource beta with income.',
    avoidIf: 'You want zero commodity exposure.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'NML',
    name: 'Neuberger Berman MLP Income Fund',
    sleeveType: 'midstream_income',
    structureLabel: 'CEF',
    yieldSource: 'MLP / midstream distributions — often K-1 or blocker structures; check tax packaging.',
    currentYield: 0.095,
    navTrend1Y: -0.07,
    premiumDiscount: 0.02,
    leverage: 1.35,
    role: 'Midstream yield sleeve; tax complexity is real.',
    mainRisks: ['NAV erosion streaks', 'Leverage', 'Tax complexity'],
    bestUseCase: 'Tax-aware investors only.',
    avoidIf: 'You hate K-1s and complexity.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'weak',
  },
  {
    ticker: 'SRV',
    name: 'NXG Cushing Midstream Energy Fund',
    sleeveType: 'midstream_income',
    structureLabel: 'CEF',
    yieldSource: 'Midstream energy cash flows — storage and logistics economics; still cyclical.',
    currentYield: 0.085,
    navTrend1Y: -0.02,
    premiumDiscount: 0.04,
    leverage: 1.2,
    role: 'Midstream carry with fund-structure frictions.',
    mainRisks: ['Commodity softness', 'Dividend cuts in stress', 'CEF premium'],
    bestUseCase: 'When midstream is a deliberate strategic bet.',
    avoidIf: 'You need non-cyclical income.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'KYN',
    name: 'Kayne Anderson Energy Infrastructure Fund',
    sleeveType: 'midstream_income',
    structureLabel: 'CEF',
    yieldSource: 'Energy infrastructure portfolio — pipelines and related assets; closed-end fund leverage applies.',
    currentYield: 0.09,
    navTrend1Y: -0.04,
    premiumDiscount: 0.06,
    leverage: 1.25,
    role: 'Established midstream CEF print.',
    mainRisks: ['Commodity correlation', 'Leverage', 'Regulatory'],
    bestUseCase: 'Energy infrastructure sleeve sizing.',
    avoidIf: 'You are overweight energy already.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
  },
  {
    ticker: 'JEPI',
    name: 'JPMorgan Equity Premium Income ETF',
    sleeveType: 'option_income',
    structureLabel: 'ETF',
    yieldSource: 'Equity portfolio plus active covered-call premium.',
    currentYield: 0.075,
    secYield: 0.074,
    navTrend1Y: 0.08,
    role: 'Lower-vol tilt equity sleeve with call-writing drag on runaway rallies.',
    mainRisks: ['Capped upside in melt-ups', 'Distribution fluctuates'],
    bestUseCase: 'Equity income without full beta in calm tape.',
    avoidIf: 'You need full index upside.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'strong',
    expenseRatio: 0.0035,
  },
  {
    ticker: 'JEPQ',
    name: 'JPMorgan Nasdaq Equity Premium Income ETF',
    sleeveType: 'option_income',
    structureLabel: 'ETF',
    yieldSource: 'Nasdaq-100 aligned sleeve with active call writing.',
    currentYield: 0.078,
    navTrend1Y: 0.09,
    role: 'Growth-tilt option-income; same playbook caveats as JEPI.',
    mainRisks: ['Tech concentration', 'Call overwrite cap'],
    bestUseCase: 'Income with growth bias.',
    avoidIf: 'You fear concentrated mega-cap risk.',
    dataAsOf: '2026-03-01',
    sourceLabel: 'Phase 1 static sample',
    confidence: 'illustrative',
    distributionQuality: 'mixed',
    expenseRatio: 0.0035,
  },
];

export const GHOSTYIELD_SCORED_CANDIDATES = scoreCandidates(GHOSTYIELD_RAW_CANDIDATES);
